# Generated by Django 5.1.15 on 2026-08-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='SMTP 服务器')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP 端口')),
                ('username', models.CharField(max_length=254, verbose_name='发信账号')),
                ('password_encrypted', models.TextField(blank=True, editable=False, verbose_name='加密后的授权密码')),
                ('from_email', models.EmailField(max_length=254, verbose_name='发件人邮箱')),
                ('use_tls', models.BooleanField(default=True, verbose_name='使用 TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='使用 SSL')),
                ('timeout', models.PositiveSmallIntegerField(default=20, verbose_name='连接超时（秒）')),
                ('test_recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='测试收件邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用此发信配置')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件发送配置',
                'verbose_name_plural': '邮件发送配置',
            },
        ),
    ]
