# Generated by Django 5.1.15 on 2026-03-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(default='/media/uploads/', max_length=200, verbose_name='默认文件存储路径')),
                ('allow_video', models.BooleanField(default=True, verbose_name='允许上传视频音频文件')),
                ('max_upload_size', models.IntegerField(default=100, verbose_name='单文件最大上传限制 (MB)')),
            ],
            options={
                'verbose_name': '存储与安全配置',
                'verbose_name_plural': '存储与安全配置',
            },
        ),
    ]
