# Generated by Django 5.1.15 on 2026-03-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': '全局运转设置', 'verbose_name_plural': '全局运转设置'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/branding/', verbose_name='网页小图标 (Favicon)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='默认 Meta Description'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='默认 Meta Keywords'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/branding/', verbose_name='网站Logo'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='企业管理系统', max_length=255, verbose_name='网站全局标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='allow_video',
            field=models.BooleanField(default=True, verbose_name='允许上传视频音频'),
        ),
    ]
