# Generated by Django 5.1.15 on 2026-03-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_settings', '0004_add_aliyun_sync_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Global settings', 'verbose_name_plural': 'Global settings'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_access_key_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Aliyun AccessKey ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_access_key_secret',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Aliyun AccessKey Secret'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_cms_metrics',
            field=models.CharField(blank=True, default='CPUUtilization,InternetIn,InternetOut', max_length=500, verbose_name='Aliyun CMS metrics (comma separated)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_cms_namespace',
            field=models.CharField(blank=True, default='acs_ecs_dashboard', max_length=64, verbose_name='Aliyun CMS namespace'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_dns_domains',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Aliyun DNS domains (comma separated)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_dns_region',
            field=models.CharField(blank=True, default='cn-hangzhou', max_length=32, verbose_name='Aliyun DNS Region'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_region',
            field=models.CharField(blank=True, default='cn-hangzhou', max_length=32, verbose_name='Aliyun Region'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='allow_video',
            field=models.BooleanField(default=True, verbose_name='Allow video/audio'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/branding/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='max_upload_size',
            field=models.IntegerField(default=100, verbose_name='Max upload size (MB)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Default meta description'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Default meta keywords'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/branding/', verbose_name='Site logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='CMS', max_length=255, verbose_name='Site title'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='storage_path',
            field=models.CharField(default='/media/uploads/', max_length=200, verbose_name='Storage path'),
        ),
    ]
