# Generated by Django 5.1.15 on 2026-03-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_settings', '0005_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': '全局运转设置', 'verbose_name_plural': '全局运转设置'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_access_key_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='阿里云 AccessKey ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_access_key_secret',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='阿里云 AccessKey Secret'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_cms_metrics',
            field=models.CharField(blank=True, default='CPUUtilization,InternetIn,InternetOut', max_length=500, verbose_name='阿里云 CMS 指标（逗号分隔）'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_cms_namespace',
            field=models.CharField(blank=True, default='acs_ecs_dashboard', max_length=64, verbose_name='阿里云 CMS Namespace'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_dns_domains',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='阿里云 DNS 域名（逗号分隔）'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_dns_region',
            field=models.CharField(blank=True, default='cn-hangzhou', max_length=32, verbose_name='阿里云 DNS Region'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='阿里云最近同步时间'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_last_sync_message',
            field=models.TextField(blank=True, default='', verbose_name='阿里云最近同步信息'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_last_sync_status',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='阿里云最近同步状态'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aliyun_region',
            field=models.CharField(blank=True, default='cn-hangzhou', max_length=32, verbose_name='阿里云 Region'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='allow_video',
            field=models.BooleanField(default=True, verbose_name='允许上传视频/音频'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/branding/', verbose_name='网站图标'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='max_upload_size',
            field=models.IntegerField(default=100, verbose_name='单文件最大上传限制（MB）'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='默认 Meta Description'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='默认 Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/branding/', verbose_name='网站 Logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='企业内容管理系统', max_length=255, verbose_name='网站标题'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='storage_path',
            field=models.CharField(default='/media/uploads/', max_length=200, verbose_name='默认文件存储路径'),
        ),
    ]
