# Generated by Django 5.1.15 on 2026-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sys_settings", "0006_alter_sitesetting_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="ai_generate_description_prompt",
            field=models.TextField(
                default="你是一个 SEO 写作专家。请根据文章内容生成 3 个吸引人的 SEO 描述（description）。\n要求：每个描述 80-160 字，包含核心关键词，有吸引力，能引发用户点击。\n输出 JSON 对象，字段为 `descriptions` 数组，每项包含 `text`（描述文本）和 `reason`（生成理由）。",
                verbose_name="AI 描述生成 Prompt",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_generate_model",
            field=models.CharField(default="Qwen/Qwen2.5-72B-Instruct", max_length=200, verbose_name="AI 四项生成默认模型"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_generate_model_options",
            field=models.JSONField(blank=True, default=list, verbose_name="AI 四项生成可选模型列表"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_generate_slug_prompt",
            field=models.TextField(
                default="你是一个 SEO 专家。请根据文章标题和内容生成 5 个适合 SEO 的 URL slug。\n要求：全部小写，用连字符分隔，不能有特殊字符，不超过 60 字符。\n输出 JSON 对象，字段为 `slugs` 数组，每项包含 `text`（slug）和 `reason`（生成理由）。",
                verbose_name="AI Slug 生成 Prompt",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_generate_tags_prompt",
            field=models.TextField(
                default="你是一个内容标签专家。请根据文章内容提取 8-10 个相关标签。\n要求：标签要有代表性，涵盖主题、领域、关键技术等维度。\n输出 JSON 对象，字段为 `tags` 数组，每项包含 `name`（标签名）和 `reason`（提取理由）。",
                verbose_name="AI 标签生成 Prompt",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_generate_title_prompt",
            field=models.TextField(
                default="你是一个标题党大师。请根据文章内容生成 5 个吸引点击的爆款标题。\n要求：每个标题不超过 30 字，包含核心关键词，有吸引力。\n输出 JSON 对象，字段为 `titles` 数组，每项包含 `text`（标题）和 `reason`（生成理由）。",
                verbose_name="AI 标题生成 Prompt",
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("sys_settings", "SiteSetting").objects.update(
                ai_generate_model_options=[
                    "Qwen/Qwen2.5-72B-Instruct",
                    "deepseek-ai/DeepSeek-V3",
                    "Qwen/Qwen2.5-32B-Instruct",
                ]
            ),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
