# Generated by Django 5.1.15 on 2026-05-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sys_settings", "0007_add_ai_generation_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="ai_alt_prompt",
            field=models.TextField(
                default="请基于图片与文章上下文生成适合 SEO 和可访问性的图片 alt 文本，输出 JSON 对象。字段必须包含 `alt_text`。",
                verbose_name="AI Alt Prompt",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_faq_prompt",
            field=models.TextField(
                default="请基于文章内容生成 3 组适合 SEO FAQ 的问答，输出 JSON 对象，字段必须包含 `faq` 数组。每项必须包含 `question` 和 `answer`。",
                verbose_name="AI FAQ Prompt",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_internal_links_prompt",
            field=models.TextField(
                default="请基于文章内容和候选文章列表推荐 3-5 个内链，输出 JSON 对象，字段必须包含 `links` 数组。每项必须包含 `title`、`url`、`reason`。",
                verbose_name="AI 内链推荐 Prompt",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_metadata_prompt",
            field=models.TextField(
                default="请返回 JSON 对象，字段必须包含 `title`、`description`、`canonical`、`robots`、`og_title`、`og_description`。输出内容用于 Django SEO Metadata 建议，不要生成额外解释。",
                verbose_name="AI Metadata Prompt",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_review_model",
            field=models.CharField(default="Qwen/Qwen2.5-72B-Instruct", max_length=200, verbose_name="AI 审核与扩展生成默认模型"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="ai_review_prompt",
            field=models.TextField(
                default="请基于以下文章内容给出 1-3 条 SEO 编辑建议，输出 JSON 对象，字段必须包含 `suggestions` 数组。每条 suggestion 必须包含 `type`、`severity`、`title`、`reason`、`patches`。patch 必须包含 `operation`、`target_block_id`、`new_text`，可选 `old_text`、`reason`。优先生成 metadata 或 body_replace 建议。",
                verbose_name="AI 审核 Prompt",
            ),
        ),
    ]
