# Generated by Django 5.1.15 on 2026-06-03 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0013_frontendcontentsetting'),
        ('sys_settings', '0013_sitesetting_homepage_featured_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_solution_article_1',
            field=models.ForeignKey(blank=True, help_text='用于首页解决方案区第一条，前台会读取文章分类、标题和摘要。', limit_choices_to={'status': 'published'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simple_cms.article', verbose_name='首页解决方案一文章'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_solution_article_2',
            field=models.ForeignKey(blank=True, help_text='用于首页解决方案区第二条，前台会读取文章分类、标题和摘要。', limit_choices_to={'status': 'published'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simple_cms.article', verbose_name='首页解决方案二文章'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_solution_article_3',
            field=models.ForeignKey(blank=True, help_text='用于首页解决方案区第三条，前台会读取文章分类、标题和摘要。', limit_choices_to={'status': 'published'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simple_cms.article', verbose_name='首页解决方案三文章'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_solution_article_4',
            field=models.ForeignKey(blank=True, help_text='用于首页解决方案区第四条，前台会读取文章分类、标题和摘要。', limit_choices_to={'status': 'published'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simple_cms.article', verbose_name='首页解决方案四文章'),
        ),
    ]
