# Generated by Django 5.1.15 on 2026-06-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_settings', '0014_sitesetting_homepage_solution_article_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_case_logo_wall_image',
            field=models.ImageField(blank=True, help_text='用于官网首页底部展示客户案例 LOGO 墙，建议上传横向大图。', null=True, upload_to='settings/homepage/', verbose_name='首页客户案例 LOGO 墙图片'),
        ),
    ]
