# Generated by Django 5.1.15 on 2026-08-12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sys_settings", "0015_sitesetting_homepage_case_logo_wall_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_description_1",
            field=models.CharField(default="在 AI 测试资料中选中制度文件，从右键菜单进入 AI 助手，问题和资料上下文同步带入。", max_length=240, verbose_name="场景一遮罩说明"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_description_2",
            field=models.CharField(default="新建智能体后直接选择 AI 解决方案文档作为知识库，再围绕企业资料进行问答。", max_length=240, verbose_name="场景二遮罩说明"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_description_3",
            field=models.CharField(default="在 AI 助手管理后台查看模型服务、模型选择和调用参数，按企业环境配置。", max_length=240, verbose_name="场景三遮罩说明"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_description_4",
            field=models.CharField(default="上传 Word 或 TXT 后查看解析状态，并在 RAG 检索增强中确认资料可被召回。", max_length=240, verbose_name="场景四遮罩说明"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_highlights_1",
            field=models.CharField(blank=True, default="员工考勤管理制度\n答案引用当前资料", help_text="每行一条卖点，留空则不展示卖点。", max_length=160, verbose_name="场景一遮罩卖点"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_highlights_2",
            field=models.CharField(blank=True, default="", help_text="每行一条卖点，留空则不展示卖点。", max_length=160, verbose_name="场景二遮罩卖点"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_highlights_3",
            field=models.CharField(blank=True, default="", help_text="每行一条卖点，留空则不展示卖点。", max_length=160, verbose_name="场景三遮罩卖点"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_highlights_4",
            field=models.CharField(blank=True, default="", help_text="每行一条卖点，留空则不展示卖点。", max_length=160, verbose_name="场景四遮罩卖点"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_title_1",
            field=models.CharField(default="右键制度文件，直接开始提问", max_length=80, verbose_name="场景一遮罩标题"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_title_2",
            field=models.CharField(default="配置智能体，关联 AI 解决方案知识库", max_length=80, verbose_name="场景二遮罩标题"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_title_3",
            field=models.CharField(default="后台统一管理模型服务与参数", max_length=80, verbose_name="场景三遮罩标题"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_title_4",
            field=models.CharField(default="上传资料，完成解析并用于 RAG 检索", max_length=80, verbose_name="场景四遮罩标题"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_video_1",
            field=models.FileField(blank=True, help_text="上传后替换官网演示场景一。支持 MP4、WebM、Ogv，建议使用无音轨 H.264 MP4。", null=True, upload_to="settings/homepage/ai-drive/", validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["mp4", "webm", "ogv"])], verbose_name="AI 网盘演示视频一"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_video_2",
            field=models.FileField(blank=True, help_text="上传后替换官网演示场景二。支持 MP4、WebM、Ogv，建议使用无音轨 H.264 MP4。", null=True, upload_to="settings/homepage/ai-drive/", validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["mp4", "webm", "ogv"])], verbose_name="AI 网盘演示视频二"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_video_3",
            field=models.FileField(blank=True, help_text="上传后替换官网演示场景三。支持 MP4、WebM、Ogv，建议使用无音轨 H.264 MP4。", null=True, upload_to="settings/homepage/ai-drive/", validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["mp4", "webm", "ogv"])], verbose_name="AI 网盘演示视频三"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_ai_drive_demo_video_4",
            field=models.FileField(blank=True, help_text="上传后替换官网演示场景四。支持 MP4、WebM、Ogv，建议使用无音轨 H.264 MP4。", null=True, upload_to="settings/homepage/ai-drive/", validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["mp4", "webm", "ogv"])], verbose_name="AI 网盘演示视频四"),
        ),
    ]
