# Generated by Codex on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DnsDomainStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain_name", models.CharField(max_length=128, verbose_name="域名")),
                ("timestamp", models.DateTimeField(verbose_name="统计时间")),
                ("request_count", models.PositiveIntegerField(default=0, verbose_name="请求量")),
                ("captured_at", models.DateTimeField(auto_now_add=True, verbose_name="采集时间")),
            ],
            options={
                "verbose_name": "DNS 统计",
                "verbose_name_plural": "DNS 统计",
                "ordering": ["-timestamp"],
                "unique_together": {("domain_name", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="EcsInstanceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instance_id", models.CharField(max_length=64, unique=True, verbose_name="实例ID")),
                ("instance_name", models.CharField(blank=True, max_length=128, verbose_name="实例名称")),
                ("status", models.CharField(blank=True, max_length=32, verbose_name="状态")),
                ("instance_type", models.CharField(blank=True, max_length=64, verbose_name="规格")),
                ("cpu", models.PositiveIntegerField(blank=True, null=True, verbose_name="CPU")),
                ("memory", models.PositiveIntegerField(blank=True, null=True, verbose_name="内存(MB)")),
                ("public_ip", models.CharField(blank=True, max_length=128, verbose_name="公网IP")),
                ("private_ip", models.CharField(blank=True, max_length=128, verbose_name="私网IP")),
                ("region_id", models.CharField(blank=True, max_length=32, verbose_name="区域")),
                ("zone_id", models.CharField(blank=True, max_length=32, verbose_name="可用区")),
                ("os_name", models.CharField(blank=True, max_length=128, verbose_name="系统")),
                ("expired_time", models.DateTimeField(blank=True, null=True, verbose_name="到期时间")),
                ("captured_at", models.DateTimeField(auto_now=True, verbose_name="采集时间")),
            ],
            options={
                "verbose_name": "ECS 实例",
                "verbose_name_plural": "ECS 实例",
                "ordering": ["-captured_at", "instance_name"],
            },
        ),
        migrations.CreateModel(
            name="EcsMetricPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instance_id", models.CharField(max_length=64, verbose_name="实例ID")),
                ("metric_name", models.CharField(max_length=64, verbose_name="指标")),
                ("timestamp", models.DateTimeField(verbose_name="时间点")),
                ("value", models.FloatField(blank=True, null=True, verbose_name="值")),
                ("period", models.PositiveIntegerField(default=60, verbose_name="周期")),
                (
                    "namespace",
                    models.CharField(default="acs_ecs_dashboard", max_length=64, verbose_name="命名空间"),
                ),
                ("region_id", models.CharField(blank=True, max_length=32, verbose_name="区域")),
                ("captured_at", models.DateTimeField(auto_now_add=True, verbose_name="采集时间")),
            ],
            options={
                "verbose_name": "ECS 指标",
                "verbose_name_plural": "ECS 指标",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="ecsmetricpoint",
            index=models.Index(fields=["instance_id", "metric_name", "timestamp"], name="aliyun_moni_instance_0d0c52_idx"),
        ),
    ]
