# Generated by Django 5.1.15 on 2026-05-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnsdomainstat',
            options={'ordering': ['-timestamp'], 'verbose_name': 'DNS 域名', 'verbose_name_plural': 'DNS 域名'},
        ),
        migrations.AlterModelOptions(
            name='ecsinstancesnapshot',
            options={'ordering': ['expired_time', 'instance_name'], 'verbose_name': 'ECS 实例', 'verbose_name_plural': 'ECS 实例'},
        ),
        migrations.RenameIndex(
            model_name='ecsmetricpoint',
            new_name='aliyun_moni_instanc_4dadc3_idx',
            old_name='aliyun_moni_instance_0d0c52_idx',
        ),
        migrations.AlterField(
            model_name='ecsinstancesnapshot',
            name='instance_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='实例 ID'),
        ),
        migrations.AlterField(
            model_name='ecsinstancesnapshot',
            name='private_ip',
            field=models.CharField(blank=True, max_length=128, verbose_name='私网 IP'),
        ),
        migrations.AlterField(
            model_name='ecsinstancesnapshot',
            name='public_ip',
            field=models.CharField(blank=True, max_length=128, verbose_name='公网 IP'),
        ),
        migrations.AlterField(
            model_name='ecsmetricpoint',
            name='instance_id',
            field=models.CharField(max_length=64, verbose_name='实例 ID'),
        ),
    ]
