# Generated by Django 5.1.15 on 2026-03-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0002_alter_category_options_article_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='用于搜索引擎抓取，若不填则默认截取正文', verbose_name='独立 SEO Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='若设置未来的时间，将在此时间后才对外展示', null=True, verbose_name='定时发布时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已下线/归档')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
