# Generated by Django 5.1.15 on 2026-03-10 07:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0003_remove_article_is_published_article_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文内容'),
        ),
    ]
