# Generated by Codex on 2026-03-16

from django.db import migrations, models
from django.utils.text import slugify


def populate_article_slugs(apps, schema_editor):
    Article = apps.get_model("simple_cms", "Article")
    existing = set(
        Article.objects.exclude(slug__isnull=True).exclude(slug="").values_list("slug", flat=True)
    )

    for article in Article.objects.filter(models.Q(slug__isnull=True) | models.Q(slug="")):
        base = slugify(article.title, allow_unicode=True) or "article"
        candidate = base
        suffix = 1
        while candidate in existing:
            suffix += 1
            candidate = f"{base}-{suffix}"
        article.slug = candidate
        article.save(update_fields=["slug"])
        existing.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("simple_cms", "0004_alter_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                help_text="Leave blank to auto-generate from title.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="SEO URL",
            ),
        ),
        migrations.RunPython(populate_article_slugs, migrations.RunPython.noop),
    ]
