# Generated by Codex on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_cms", "0005_add_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                help_text="Leave blank to auto-generate from title.",
                max_length=255,
                null=False,
                unique=True,
                verbose_name="SEO URL",
            ),
        ),
    ]
