# Generated by Codex on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_cms", "0006_alter_article_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSlugHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name="历史SEO URL"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录时间")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slug_histories",
                        to="simple_cms.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章历史链接",
                "verbose_name_plural": "文章历史链接",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title_snapshot", models.CharField(max_length=255, verbose_name="标题快照")),
                (
                    "slug_snapshot",
                    models.SlugField(allow_unicode=True, max_length=255, verbose_name="SEO URL快照"),
                ),
                ("body_snapshot", models.TextField(verbose_name="正文快照")),
                (
                    "status_snapshot",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布"), ("archived", "已下线/归档")],
                        max_length=20,
                        verbose_name="状态快照",
                    ),
                ),
                (
                    "publish_date_snapshot",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间快照"),
                ),
                (
                    "meta_description_snapshot",
                    models.TextField(blank=True, verbose_name="SEO描述快照"),
                ),
                (
                    "category_name_snapshot",
                    models.CharField(blank=True, max_length=100, verbose_name="分类快照"),
                ),
                ("changed_fields", models.CharField(max_length=255, verbose_name="变更字段")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="保存时间")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="simple_cms.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章版本",
                "verbose_name_plural": "文章版本",
                "ordering": ["-created_at"],
            },
        ),
    ]
