# Generated by Codex on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_cms", "0007_article_slug_history_and_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="SEO 标题"),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255, verbose_name="SEO 关键词"),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description",
            field=models.TextField(blank=True, verbose_name="SEO 描述"),
        ),
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="排序权重"),
        ),
        migrations.AddField(
            model_name="article",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="置顶"),
        ),
        migrations.AddField(
            model_name="article",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="置顶时间"),
        ),
        migrations.AddField(
            model_name="article",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="排序权重"),
        ),
    ]
