# Generated by Django 5.1.15 on 2026-05-09 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_imageitem_alt_text'),
        ('simple_cms', '0008_article_ordering_and_category_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='标签缩略名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, help_text='供新版编辑器和 SEO 渲染复用的 HTML 缓存。', verbose_name='正文 HTML 缓存'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_json',
            field=models.JSONField(blank=True, default=dict, help_text='编辑真相源，遵循 TipTap v1 契约。', verbose_name='TipTap 内容 JSON'),
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='simple_cms.article')),
            ],
            options={
                'verbose_name': 'FAQ 条目',
                'verbose_name_plural': 'FAQ 条目',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('robots', models.CharField(default='index,follow', max_length=50, verbose_name='Robots')),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='OG 标题')),
                ('og_description', models.TextField(blank=True, verbose_name='OG 描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_metadata', to='simple_cms.article')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_og_articles', to='media_library.imageitem', verbose_name='OG 图片')),
            ],
            options={
                'verbose_name': 'SEO 元数据',
                'verbose_name_plural': 'SEO 元数据',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='simple_cms.tag', verbose_name='标签'),
        ),
    ]
