# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_cms", "0009_tag_article_content_html_article_content_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiReviewRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="审核运行 ID")),
                ("schema_version", models.CharField(default="v1", max_length=10, verbose_name="契约版本")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("provider", models.CharField(max_length=100, verbose_name="提供方")),
                ("model", models.CharField(max_length=100, verbose_name="模型")),
                ("prompt_version", models.CharField(max_length=50, verbose_name="Prompt 版本")),
                ("trace_id", models.CharField(blank=True, max_length=128, null=True, verbose_name="追踪 ID")),
                ("token_usage", models.JSONField(blank=True, default=dict, verbose_name="Token 使用量")),
                ("error", models.JSONField(blank=True, null=True, verbose_name="错误详情")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_review_runs",
                        to="simple_cms.article",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 审核运行",
                "verbose_name_plural": "AI 审核运行",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("suggestion_id", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="建议 ID")),
                ("schema_version", models.CharField(default="v1", max_length=10, verbose_name="契约版本")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("metadata", "SEO 元数据"),
                            ("faq", "FAQ"),
                            ("internal_link", "内链"),
                            ("semantic_keyword", "语义关键词"),
                            ("body_insert", "正文插入"),
                            ("body_delete", "正文删除"),
                            ("body_replace", "正文替换"),
                            ("alt_text", "图片 Alt"),
                        ],
                        max_length=50,
                        verbose_name="建议类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("edited", "已编辑"),
                            ("expired", "已过期"),
                            ("failed", "失败"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        max_length=20,
                        verbose_name="严重级别",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("reason", models.TextField(verbose_name="原因")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="结构化负载")),
                ("source_chunks", models.JSONField(blank=True, default=list, verbose_name="来源片段")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="simple_cms.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="simple_cms.aireviewrun",
                        verbose_name="审核运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 建议",
                "verbose_name_plural": "AI 建议",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiPatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("patch_id", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="补丁 ID")),
                (
                    "patch_schema_version",
                    models.CharField(default="v1", max_length=10, verbose_name="补丁契约版本"),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("insert_after", "插入后面"),
                            ("delete", "删除"),
                            ("replace_text", "替换文本"),
                            ("alt_text", "Alt 文本"),
                        ],
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                ("target_block_id", models.CharField(max_length=100, verbose_name="目标块 ID")),
                ("content_hash", models.CharField(max_length=255, verbose_name="内容哈希")),
                ("old_text", models.TextField(blank=True, null=True, verbose_name="旧文本")),
                ("new_text", models.TextField(blank=True, null=True, verbose_name="新文本")),
                ("new_block", models.JSONField(blank=True, null=True, verbose_name="新块内容")),
                ("position", models.IntegerField(blank=True, null=True, verbose_name="插入位置")),
                ("reason", models.TextField(blank=True, null=True, verbose_name="说明")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patches",
                        to="simple_cms.aisuggestion",
                        verbose_name="建议",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 补丁",
                "verbose_name_plural": "AI 补丁",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(fields=["article", "status"], name="simple_cms__article_9d7804_idx"),
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(fields=["run", "status"], name="simple_cms__run_id_1c08bb_idx"),
        ),
        migrations.AddIndex(
            model_name="aipatch",
            index=models.Index(fields=["suggestion", "operation"], name="simple_cms__suggest_509502_idx"),
        ),
    ]
