# Generated by Django 5.1.15 on 2026-05-09 13:30

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_cms", "0009_tag_article_content_html_article_content_json_and_more"),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(choices=[("article", "文章"), ("faq", "FAQ"), ("category", "分类页"), ("tag", "标签页"), ("product", "产品页"), ("service", "服务页"), ("brand", "品牌页"), ("case", "案例页"), ("term", "术语库"), ("seo_rule", "SEO 规则")], max_length=32, verbose_name="来源类型")),
                ("source_id", models.PositiveBigIntegerField(verbose_name="来源 ID")),
                ("title", models.CharField(max_length=255, verbose_name="来源标题")),
                ("url", models.CharField(max_length=500, verbose_name="来源 URL")),
                ("content_hash", models.CharField(max_length=71, verbose_name="内容哈希")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("last_indexed_at", models.DateTimeField(blank=True, null=True, verbose_name="最近索引时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={"verbose_name": "知识来源", "verbose_name_plural": "知识来源", "ordering": ["source_type", "source_id"]},
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_index", models.PositiveIntegerField(verbose_name="分块序号")),
                ("chunk_text", models.TextField(verbose_name="分块文本")),
                ("chunk_hash", models.CharField(max_length=71, verbose_name="分块哈希")),
                ("embedding", pgvector.django.VectorField(blank=True, dimensions=1536, null=True, verbose_name="向量")),
                ("embedding_model", models.CharField(blank=True, max_length=255, verbose_name="向量模型")),
                ("embedding_dimensions", models.PositiveIntegerField(default=1536, verbose_name="向量维度")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="附加元数据")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="simple_cms.knowledgesource", verbose_name="知识来源")),
            ],
            options={"verbose_name": "知识分块", "verbose_name_plural": "知识分块", "ordering": ["source_id", "chunk_index"]},
        ),
        migrations.AddConstraint(
            model_name="knowledgesource",
            constraint=models.UniqueConstraint(fields=("source_type", "source_id"), name="uniq_knowledge_source_type_id"),
        ),
        migrations.AddConstraint(
            model_name="knowledgechunk",
            constraint=models.UniqueConstraint(fields=("source", "chunk_index"), name="uniq_knowledge_chunk_source_index"),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(fields=["is_active", "source"], name="simple_cms__knowledg_iact_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(fields=["chunk_hash"], name="simple_cms__knowledg_hash_idx"),
        ),
    ]
