# Generated by Codex on 2026-05-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_cms", "0010_ai_review_models"),
        ("simple_cms", "0011_knowledge_source_knowledge_chunk"),
    ]

    operations = []
