# Generated by Django 5.1.15 on 2026-05-09 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0012_merge_20260509_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(default='v1', max_length=10, verbose_name='契约版本')),
                ('source', models.CharField(choices=[('gsc', 'Google Search Console'), ('ga4', 'Google Analytics 4'), ('internal', '站内事件')], max_length=20, verbose_name='数据来源')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='展示次数')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='点击次数')),
                ('ctr', models.FloatField(default=0, verbose_name='点击率')),
                ('average_position', models.FloatField(default=0, verbose_name='平均排名')),
                ('pageviews', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('avg_time_on_page', models.PositiveIntegerField(default=0, verbose_name='平均停留秒数')),
                ('bounce_rate', models.FloatField(default=0, verbose_name='跳出率')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='转化次数')),
                ('internal_clicks', models.PositiveIntegerField(default=0, verbose_name='站内点击')),
                ('ai_acceptance_rate', models.FloatField(default=0, verbose_name='AI 建议采纳率')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='扩展负载')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='simple_cms.article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '监控快照',
                'verbose_name_plural': '监控快照',
                'ordering': ['-snapshot_date', 'article_id', 'source'],
                'indexes': [models.Index(fields=['snapshot_date', 'source'], name='analytics_date_src_idx'), models.Index(fields=['article', 'snapshot_date'], name='analytics_art_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'source', 'snapshot_date'), name='uniq_analytics_article_source_date')],
            },
        ),
    ]
