# Generated by Django 5.1.15 on 2026-05-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt 文本'),
        ),
    ]
